baseURL: "https://yogheswaran-a.github.io/personalwebsite/"
title: Yoghes Waran 🤖
paginate: 20
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

pygmentsUseClasses: false
pygmentsCodefences: true
pygmentsStyle: "fortnite"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Yoghes Waran
  description: "My Personal Website And Notes"
  keywords: [Blog, Portfolio, PaperMod,Yoghes,Waran,Yoghes Waran,NIT Trichy]
  author: Yoghes Waran
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  math: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    #favicon: "<link rel="icon" href="E:/personalwebsite/personalwebsite/static/images/favicon_poke_ball.ico">"
    #favicon16x16: #"<link / abs url>"
    #favicon32x32: #"<link / abs url>"
    #apple_touch_icon:  #"<link rel="icon" href="https://yogheswaran.github.io/personalwebsite/favicon_poke_ball.ico">"
    #safari_pinned_tab:  #"<link rel="icon" href="https://yogheswaran.github.io/personalwebsite/favicon_poke_ball.ico">"

  label:
    text: "🌎 Yoghes's Workspace"
    icon: #"images/homepage/camera.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true
    title: "Vanakkam Namaste Welcome!👋" # optional default will be site title
    subtitle: "A curious wanderer 🤖 of this planet seeking the best possible answers while navigating through various challenges. In this narrative, I try to document my journey of exploration, discovery and invention as I strive to elevate my understanding across multiple dimensions."
    imageUrl: "images/homepage/profile_pic.png" # optional
    imageTitle: "India Gate, Delhi" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Blogs
        url: "blogs"
      - name: CV
        url: "resume.pdf"

  socialIcons: # optional
  #  - name: "<platform>"
  #    url: "<link>"
  #  - name: "<platform 2>"
  #    url: "<link2>"

  # home-info mode
  homeInfoParams:
    Title: "Konnichiwa! \U0001F44B"
    Content: "This is the website of **Yoghes Waran.**"

  socialIcons:
    #- name: x
    #  url: "https://x.com/"
    - name: stackoverflow
      url: "https://stats.stackexchange.com/users/393683/yo-wa"
    - name: github
      url: "https://github.com/yogheswaran-A"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "" #"https://github.com/<path_to_repo>/content"
    Text: "" #"Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    #limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series  
menu:
  main:
    - identifier: cv
      name: CV
      url: resume.pdf
      weight: 1
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 2   
    - identifier: search
      name: Search
      url: search/
      weight: 3
    
    #- identifier: categories
    #  name: categories
    #  url: /categories/
    #  weight: 10
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 20
    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
    # - identifier: about
    #  name: About
    #  url: /about/
    #  weight: 1
    #- identifier: projects
    #  name: Projects
    #  url: /projects/
    #  weight: 3
    #- identifier: 3D Modelling
    #  name: 3D Modelling
    #  url: /3D Modelling/
    #  weight: 4
    #- identifier: Drawing
    #  name: Drawing
    #  url: /Drawing/
    #  weight: 5
    #- identifier: Poems
    #  name: Poems
    #  url: /poems/
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search